[package]
name = "hawdb-explain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hawdb-core = { path = "../core" }
hawdb-executor = { path = "../executor" }
hawdb-optimizer = { path = "../optimizer" }
hawdb-plan = { path = "../plan" }
hawdb-plan-cache = { path = "../plan-cache" }
hawdb-qos = { path = "../qos" }
hawdb-storage = { path = "../storage" }
unicode-width = "0.2"
