[package]
name = "hawdb-optimizer"
version.workspace = true
edition = "2024"
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
hawdb-cascades = { path = "../cascades", version = "0.4.0" }
hawdb-optimizer-graph = { path = "../optimizer-graph", version = "0.4.0" }
hawdb-optimizer-relational = { path = "../optimizer-relational", version = "0.4.0" }
hawdb-optimizer-predicate = { path = "../optimizer-predicate", version = "0.4.0" }
hawdb-optimizer-vector = { path = "../optimizer-vector", version = "0.4.0" }
