[package]
name = "skein-optimizer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde_json = "1"
skein-core = { path = "../core" }
skein-cypher = { path = "../cypher" }
skein-expression = { path = "../expression" }
skein-plan = { path = "../plan" }
