[package]
name = "hawdb-compat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde = "1"
serde_json = "1"
hawdb-analytics = { path = "../analytics", version = "0.3.0" }
hawdb-core = { path = "../core", version = "0.3.0" }
hawdb-evidence = { path = "../evidence", version = "0.3.0" }
hawdb-executor = { path = "../executor", version = "0.3.0" }
hawdb-storage = { path = "../storage", version = "0.3.0" }
