[package]
name = "hawdb-optimizer-predicate"
version.workspace = true
edition = "2024"
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
hawdb-cascades = { path = "../cascades", version = "0.3.0" }
serde_json = "1"
