[header]
builtin = "Apache-2.0"

[props]
copyright_owner = "Nowledge"
inception_year = 2026

[files]
excludes = [
    "**/*.toml",
    "**/*.yml",
    "**/*.yaml",
    "**/*.json",
    "**/*.lock",
    "**/*.sql",
    "**/BUILD.bazel",
    "**/*.bzl",
    "tests/**",
    "**/tests/**",
    "test/**",
    "**/test/**",
    "**/tests.rs",
    "**/test.rs",
    "**/*_test.rs",
    "**/*_tests.rs",
    "fixtures/**",
    "**/fixtures/**",
    "fuzz/**",
    "**/fuzz/**",
    "benches/**",
    "**/benches/**",
    "examples/**",
    "**/examples/**",
]
