[package]
name = "hawdb-runtime-tokio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hawdb-core = { path = "../core" }
hawdb-qos = { path = "../qos" }
hawdb-storage = { path = "../storage" }
tokio = { version = "1.49", features = ["rt-multi-thread", "sync", "time"] }
