[package]
name = "hawdb-plan-cache"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
hawdb-core = { path = "../core", version = "0.3.0" }
hawdb-cypher = { path = "../cypher", version = "0.3.0" }
hawdb-plan = { path = "../plan", version = "0.3.0" }

[dev-dependencies]
loom = "0.7"
hawdb-optimizer = { path = "../optimizer", version = "0.3.0" }

[features]
default = []
loom-tests = []
