[package]
name = "hawdb-plan-cache"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hawdb-core = { path = "../core" }
hawdb-cypher = { path = "../cypher" }
hawdb-plan = { path = "../plan" }

[dev-dependencies]
loom = "0.7"
hawdb-optimizer = { path = "../optimizer" }

[features]
default = []
loom-tests = []
