[package]
name = "skein-relational"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
skein-core = { path = "../core" }
skein-executor = { path = "../executor" }
skein-sql = { path = "../sql" }
skein-expression = { path = "../expression" }
skein-optimizer = { path = "../optimizer" }
skein-storage = { path = "../storage" }
