[package]
name = "hawdb-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
caseless = "0.2.2"
hawdb-core = { path = "../core" }
hawdb-expression = { path = "../expression" }
hawdb-plan = { path = "../plan" }
hawdb-plan-cache = { path = "../plan-cache" }
hawdb-sql-syntax = { path = "../sql-syntax" }
sqlparser = "0.61"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
