[package]
name = "skein-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
caseless = "0.2.2"
skein-core = { path = "../core" }
skein-plan = { path = "../plan" }
skein-sql-syntax = { path = "../sql-syntax" }
sqlparser = "0.61"
