load("@crate_index//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

test_suite(
    name = "presubmit_tests",
)

filegroup(
    name = "migration_corpus_test_data",
    testonly = True,
    srcs = glob(["fixtures/migration_*"]),
)

rust_library(
    name = "hawdb_cypher",
    crate_name = "hawdb_cypher",
    crate_root = "src/lib.rs",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    aliases = aliases(),
    deps = all_crate_deps(normal = True) + [
        "//crates/core:hawdb_core",
        "//crates/ddl:hawdb_ddl",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "hawdb_cypher_tests",
    crate = ":hawdb_cypher",
    compile_data = [":migration_corpus_test_data"],
    edition = "2024",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)

rust_test(
    name = "hawdb_cypher_backtracking_fuzz_tests",
    compile_data = [":migration_corpus_test_data"],
    args = [
        "tests::backtracking::parser_backtracking_differential_campaign",
        "--exact",
        "--ignored",
        "--nocapture",
    ],
    crate = ":hawdb_cypher",
    edition = "2024",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    tags = ["manual"],
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)
