load("@crate_index//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

test_suite(
    name = "presubmit_tests",
)

rust_library(
    name = "hawdb_analytics",
    crate_name = "hawdb_analytics",
    crate_root = "src/lib.rs",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    aliases = aliases(),
    deps = [
        "//crates/core:hawdb_core",
    ],
)

rust_test(
    name = "hawdb_analytics_tests",
    crate = ":hawdb_analytics",
    edition = "2024",
)
