[package]
name = "hawdb-qos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
hawdb-core = { path = "../core", version = "0.3.0" }
hawdb-cgroup = { path = "../cgroup", version = "0.3.0" }
sysinfo = { version = "0.38", default-features = false, features = ["system"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_System_ProcessStatus",
  "Win32_System_Threading",
] }

[dev-dependencies]
loom = "0.7"

[features]
default = []
loom-tests = []
