[package]
name = "hawdb-system-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde_json = "1"
hawdb-core = { path = "../core", version = "0.2.0" }
hawdb-executor = { path = "../executor", version = "0.2.0" }
hawdb-plan-cache = { path = "../plan-cache", version = "0.2.0" }
hawdb-query = { path = "../query", version = "0.2.0" }
hawdb-sql = { path = "../sql", version = "0.2.0" }
hawdb-storage = { path = "../storage", version = "0.2.0" }

[dev-dependencies]
loom = "0.7"

[features]
default = []
loom-tests = []
