[package]
name = "skein-system-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde_json = "1"
skein-core = { path = "../core" }
skein-executor = { path = "../executor" }
skein-plan-cache = { path = "../plan-cache" }
skein-query = { path = "../query" }
skein-sql = { path = "../sql" }
skein-storage = { path = "../storage" }

[dev-dependencies]
loom = "0.7"

[features]
default = []
loom-tests = []
