from typing import Any, Dict, List, Mapping, Optional

__version__: str

class QueryResult:
    """Materialized rows of one statement result."""

    @property
    def columns(self) -> List[str]: ...
    @property
    def row_count(self) -> int: ...
    def fetchone(self) -> Optional[Dict[str, Any]]: ...
    def fetchmany(self, size: int = 1) -> List[Dict[str, Any]]: ...
    def fetchall(self) -> List[Dict[str, Any]]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> "QueryResult": ...
    def __next__(self) -> Dict[str, Any]: ...

class Database:
    """An open HawDB database."""

    def __init__(self, path: str, read_only: bool = False) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def is_open(self) -> bool: ...
    def execute(
        self, cypher: str, params: Optional[Dict[str, Any]] = None
    ) -> QueryResult: ...
    def execute_sql(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> QueryResult: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Database": ...
    def __exit__(self, *args: object) -> bool: ...

def open(path: str, read_only: bool = False) -> Database: ...
def capabilities() -> Mapping[str, bool]:
    """Engine capabilities compiled into this extension (read-only)."""

class exceptions: ...
