from typing import Any, Dict, List, Mapping, Optional

__version__: str

class QueryResult:
    """Materialized rows of one statement result."""

    @property
    def columns(self) -> List[str]: ...
    @property
    def row_count(self) -> int: ...
    def fetchone(self) -> Optional[Dict[str, Any]]: ...
    def fetchmany(self, size: int = 1) -> List[Dict[str, Any]]: ...
    def fetchall(self) -> List[Dict[str, Any]]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> "QueryResult": ...
    def __next__(self) -> Dict[str, Any]: ...

class Database:
    """An open HawDB database."""

    def __init__(
        self, path: Optional[str] = None, read_only: bool = False
    ) -> None: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def is_open(self) -> bool: ...
    def execute(
        self, cypher: str, params: Optional[Dict[str, Any]] = None
    ) -> QueryResult: ...
    def execute_sql(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> QueryResult: ...
    def transaction(self) -> "Transaction": ...
    def read_transaction(self) -> "ReadTransaction": ...
    def close(self) -> None: ...
    def __enter__(self) -> "Database": ...
    def __exit__(self, *args: object) -> bool: ...

class Transaction:
    """An open multi-statement transaction on a Database."""

    def execute(
        self, cypher: str, params: Optional[Dict[str, Any]] = None
    ) -> QueryResult: ...
    def execute_sql(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> QueryResult: ...
    def commit(self) -> QueryResult: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> "Transaction": ...
    def __exit__(self, *args: object) -> bool: ...

class ReadTransaction:
    """A stable read-only scope on a Database."""

    def execute(
        self, cypher: str, params: Optional[Dict[str, Any]] = None
    ) -> QueryResult: ...
    def execute_sql(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> QueryResult: ...
    def close(self) -> None: ...
    def __enter__(self) -> "ReadTransaction": ...
    def __exit__(self, *args: object) -> bool: ...

def open(path: Optional[str] = None, read_only: bool = False) -> Database: ...
def capabilities() -> Mapping[str, bool]:
    """Engine capabilities compiled into this extension (read-only)."""

class exceptions: ...
