from typing import Any, Dict, List, Mapping, Optional

__version__: str

class QueryResult:
    """Materialized rows of one statement result."""

    @property
    def columns(self) -> List[str]: ...
    @property
    def row_count(self) -> int: ...
    def fetchone(self) -> Optional[Dict[str, Any]]: ...
    def fetchmany(self, size: int = 1) -> List[Dict[str, Any]]: ...
    def fetchall(self) -> List[Dict[str, Any]]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> "QueryResult": ...
    def __next__(self) -> Dict[str, Any]: ...

class Database:
    """An open HawDB database."""

    def __init__(
        self, path: Optional[str] = None, read_only: bool = False
    ) -> None: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def is_open(self) -> bool: ...
    def execute(
        self, cypher: str, params: Optional[Dict[str, Any]] = None
    ) -> QueryResult: ...
    def execute_sql(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> QueryResult: ...
    def execute_retained(
        self, cypher: str, params: Optional[Dict[str, Any]] = None,
        *, options: Optional["RetainedOptions"] = None,
    ) -> "RetainedCursor": ...
    def retained_snapshot_copy(self) -> Optional[Dict[str, int]]: ...
    def transaction(self) -> "Transaction": ...
    def read_transaction(self) -> "ReadTransaction": ...
    def close(self) -> None: ...
    def __enter__(self) -> "Database": ...
    def __exit__(self, *args: object) -> bool: ...

class Transaction:
    """An open multi-statement transaction on a Database."""

    def execute(
        self, cypher: str, params: Optional[Dict[str, Any]] = None
    ) -> QueryResult: ...
    def execute_sql(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> QueryResult: ...
    def commit(self) -> QueryResult: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> "Transaction": ...
    def __exit__(self, *args: object) -> bool: ...

class ReadTransaction:
    """A stable read-only scope on a Database."""

    def execute(
        self, cypher: str, params: Optional[Dict[str, Any]] = None
    ) -> QueryResult: ...
    def execute_sql(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> QueryResult: ...
    def close(self) -> None: ...
    def __enter__(self) -> "ReadTransaction": ...
    def __exit__(self, *args: object) -> bool: ...

def open(path: Optional[str] = None, read_only: bool = False) -> Database: ...
def capabilities() -> Mapping[str, bool]:
    """Engine capabilities compiled into this extension (read-only)."""

class exceptions: ...

class RetainedOptions:
    def __init__(self, *, batch_rows: Optional[int] = None,
                 batch_bytes: Optional[int] = None, outstanding_batches: Optional[int] = None,
                 require_source_reuse: bool = False, writable: bool = False,
                 max_result_rows: Optional[int] = None) -> None: ...

class RetainedCursor:
    def __arrow_c_schema__(self) -> Any: ...
    def __arrow_c_stream__(self, requested_schema: Optional[Any] = None) -> Any: ...
    @property
    def status(self) -> str: ...
    @property
    def column_count(self) -> int: ...
    def next_batch(self) -> Optional["RetainedBatch"]: ...
    def close(self) -> None: ...
    def schema_copy(self) -> List[Dict[str, Any]]: ...
    def profile_copy(self) -> Dict[str, Any]: ...
    def __iter__(self) -> "RetainedCursor": ...
    def __next__(self) -> "RetainedBatch": ...

class RetainedBatch:
    def __arrow_c_schema__(self) -> Any: ...
    def __arrow_c_array__(self, requested_schema: Optional[Any] = None) -> tuple[Any, Any]: ...
    @property
    def row_count(self) -> int: ...
    @property
    def physical_rows(self) -> int: ...
    @property
    def column_count(self) -> int: ...
    @property
    def status(self) -> str: ...
    def close(self) -> None: ...
    def retain(self) -> "RetainedBatch": ...
    def column(self, index: int, *, writable: bool = False, dtype: Optional[str] = None) -> "RetainedBuffer": ...
    def selection(self) -> "RetainedBuffer": ...
    def value_copy(self, column: int, row: int) -> Any: ...

class RetainedBuffer:
    @property
    def row_count(self) -> int: ...
    @property
    def physical_rows(self) -> int: ...
    @property
    def status(self) -> str: ...
    def close(self) -> None: ...
    def retain(self) -> "RetainedBuffer": ...
    def selection(self) -> "RetainedBuffer": ...
    def validity(self) -> Optional["RetainedBuffer"]: ...
    def provenance_copy(self) -> Dict[str, int]: ...
