[package]
name = "hawdb-query-policy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hawdb-core = { path = "../core" }
hawdb-cypher = { path = "../cypher" }
hawdb-optimizer = { path = "../optimizer" }
hawdb-qos = { path = "../qos" }
