use super::*;
use crate::{
    CompressedVectorSearchMode, SearchCandidateSetReport, SearchMode, SearchPredicatePushdownReport,
};
use std::collections::BTreeMap;

pub(super) fn ready_report() -> NowledgeMemSearchCandidateReport {
    NowledgeMemSearchCandidateReport {
        protocol: NOWLEDGE_MEM_SEARCH_CANDIDATE_REPORT_PROTOCOL.to_string(),
        compressed_vector_search_mode: CompressedVectorSearchMode::Disabled,
        requested_compressed_vector_search_mode: CompressedVectorSearchMode::Disabled,
        retrieval_projection_advisor: NowledgeMemRetrievalProjectionAdvisor::default(),
        retrieval_projection_advisor_blocker_codes: Vec::new(),
        mode: SearchMode::Text,
        query_embedding_dimension: Some(2),
        limit: 4,
        offset: 2,
        rank_window: Some(8),
        document_count: 9,
        filtered_document_count: 7,
        total_hits: 3,
        returned_hit_count: 1,
        returned_kind_counts: BTreeMap::from([("source_chunk".to_string(), 1)]),
        returned_missing_external_id_count: 0,
        returned_missing_source_id_count: 0,
        truncated: true,
        candidate_set: SearchCandidateSetReport {
            id_space: "fixture".to_string(),
            representation: "fixture".to_string(),
            cardinality: 3,
            exact: true,
            snapshot_source_graph_commit_epoch: Some(7),
            policy_epoch: Some(2),
            filtered_out_count: 2,
            metadata_filters: BTreeMap::new(),
            metadata_predicate_pushdown: SearchPredicatePushdownReport::default(),
        },
        filtered_out_count: 2,
        metadata_filter_count: 1,
        pushed_predicate_count: 1,
        residual_predicate_count: 0,
        segment_count: 3,
        pruned_segment_count: 1,
        scanned_segment_count: 2,
        segment_pruning_candidate_document_count: 9,
        segment_pruned_document_count: 2,
        segment_scanned_document_count: 7,
        persisted_segment_descriptor_used: true,
        physical_range_read_count: 2,
        physical_bytes_read: 256,
        retriever_backends: BTreeMap::from([("text".to_string(), "fixture".to_string())]),
        retriever_backend_selection_reasons: BTreeMap::new(),
        retriever_estimated_raw_vector_bytes: BTreeMap::new(),
        retriever_filter_selectivity_per_million: BTreeMap::new(),
        retriever_available: BTreeMap::from([
            ("text".to_string(), true),
            ("vector".to_string(), true),
        ]),
        retriever_candidate_counts: BTreeMap::from([
            ("text".to_string(), 3),
            ("vector".to_string(), 2),
        ]),
        retriever_candidate_score_sources: BTreeMap::new(),
        retriever_final_score_sources: BTreeMap::new(),
        fallback_reason_codes: vec!["fixture_fallback".to_string()],
        empty_reason_codes: Vec::new(),
        truncation_reason_codes: Vec::new(),
        projection_full_reindex_needed: false,
        projection_metadata_repair_needed: false,
        projection_source_graph_commit_epoch: Some(8),
        projection_durable_source_graph_commit_epoch: Some(7),
        projection_embedding_model: Some("model".to_string()),
        projection_embedding_version: Some("version".to_string()),
        projection_embedding_dimension: Some(2),
    }
}
