[package]
name = "hawdb-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fs2 = "0.4.3"
rayon = "1.11"
hawdb-analytics = { path = "../analytics" }
hawdb-core = { path = "../core" }
hawdb-ddl = { path = "../ddl" }
hawdb-plan = { path = "../plan" }
hawdb-qos = { path = "../qos" }
hawdb-storage = { path = "../storage" }
