load("@crate_index//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

test_suite(
    name = "presubmit_tests",
)

rust_library(
    name = "hawdb_evidence",
    crate_name = "hawdb_evidence",
    crate_root = "src/lib.rs",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    aliases = aliases(),
    deps = all_crate_deps(normal = True) + [
        "//crates/core:hawdb_core",
        "//crates/integrity:hawdb_integrity",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "hawdb_evidence_tests",
    crate = ":hawdb_evidence",
    edition = "2024",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)

rust_test(
    name = "hawdb_inventory_health_fuzz_tests",
    tags = ["manual"],
    args = [
        "inventory::differential::inventory_health_differential_campaign",
        "--exact",
        "--ignored",
        "--nocapture",
    ],
    crate = ":hawdb_evidence",
    edition = "2024",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)

rust_test(
    name = "hawdb_source_inventory_fuzz_tests",
    tags = ["manual"],
    args = [
        "query_inventory::scanner::differential::source_inventory_differential_campaign",
        "--exact",
        "--ignored",
        "--nocapture",
    ],
    crate = ":hawdb_evidence",
    edition = "2024",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)

rust_test(
    name = "hawdb_resource_profile_fuzz_tests",
    tags = ["manual"],
    args = [
        "resource_profile::tests::resource_profile_differential_campaign",
        "--exact",
        "--ignored",
        "--nocapture",
    ],
    crate = ":hawdb_evidence",
    edition = "2024",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)
