/*
 * Copyright 2026 Nowledge
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated by cbindgen. Do not edit by hand. */


#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * An open HawDB database handle. Opaque to C callers.
 */
typedef struct HawdbDatabase HawdbDatabase;

#if defined(HAWDB_BOUNDARY_PROFILING)
typedef struct BoundaryProfileSnapshot {
  uint64_t allocation_calls;
  uint64_t allocated_bytes;
  uint64_t deallocation_calls;
  uint64_t deallocated_bytes;
  uint64_t reallocation_calls;
  uint64_t live_requested_bytes;
  uint64_t process_peak_requested_bytes;
  uint64_t parameter_conversion_ns;
  uint64_t engine_call_ns;
  uint64_t result_conversion_ns;
} BoundaryProfileSnapshot;
#endif

/**
 * A byte buffer the library hands to the caller.
 *
 * `ptr` is `len` bytes of UTF-8 text; it is NUL-terminated as a courtesy
 * but `len` is authoritative and the content may not contain NUL bytes
 * anyway (JSON escapes them). The caller owns every non-NULL `ptr` and
 * releases it with [`hawdb_buffer_free`]. The library never retains or
 * reuses a buffer it has returned.
 */
typedef struct HawdbBuffer {
  char *ptr;
  uintptr_t len;
} HawdbBuffer;

#if defined(HAWDB_BOUNDARY_PROFILING)
/**
 * Developer profiling build only. This observation is not an admission ledger
 * or an allocator-capacity bound. NULL output is a no-op; no buffer is allocated.
 *
 * # Safety
 * `out` must be NULL or point to writable `BoundaryProfileSnapshot` storage.
 */
void hawdb_boundary_profile_snapshot(struct BoundaryProfileSnapshot *out);
#endif

/**
 * Open a HawDB database at `path`, creating it if needed.
 *
 * `path` is `path_len` UTF-8 bytes and must not be NULL. `options_json`
 * may be NULL or a JSON object; currently supported keys:
 * `{"read_only": bool}`.
 *
 * Returns a handle to pass to the other functions, or NULL on failure
 * with `err_out` filled. Close the handle with [`hawdb_close`].
 *
 * # Safety
 * `path` and `options_json` must be readable for `path_len` /
 * `options_len` bytes or NULL; `err_out` must be NULL or writable
 * [`HawdbBuffer`] storage. The returned handle is safe to use from
 * multiple threads; calls are serialized internally.
 */
struct HawdbDatabase *hawdb_open(const char *path,
                                 uintptr_t path_len,
                                 const char *options_json,
                                 uintptr_t options_len,
                                 struct HawdbBuffer *err_out);

/**
 * Open an independent in-memory database using the embedded facade defaults.
 * Close the returned handle with [`hawdb_close`]. Errors use the same output
 * convention as [`hawdb_open`]; this does not create a temporary on-disk store.
 *
 * # Safety
 * `err_out` must be NULL or point to writable [`HawdbBuffer`] storage.
 */
struct HawdbDatabase *hawdb_open_in_memory(struct HawdbBuffer *err_out);

/**
 * Close a database handle and release its resources.
 *
 * # Safety
 * `db` must be a handle returned by [`hawdb_open`] and not already
 * closed. Passing NULL is a no-op.
 */
void hawdb_close(struct HawdbDatabase *db);

/**
 * Run one Cypher statement.
 *
 * `cypher` is `cypher_len` UTF-8 bytes and must not be NULL.
 * `params_json` may be NULL or a JSON object mapping `$name` parameter
 * names to values (`null`, bool, number, string, array, object, or the
 * tagged forms `{"$binary": "<base64>"}` and `{"$uuid": "<text>"}`).
 *
 * On success returns true and `result_out` receives the result envelope
 * `{"columns": [...], "rows": [[...], ...]}`; on failure returns false
 * and `err_out` receives `{"kind", "message"}`.
 *
 * # Safety
 * `db` must be a live [`hawdb_open`] handle; `cypher` and `params_json`
 * must be readable for `cypher_len` / `params_len` bytes or NULL;
 * `result_out` and `err_out` must be NULL or writable [`HawdbBuffer`]
 * storage. A false return leaves the handle usable.
 */
bool hawdb_query(struct HawdbDatabase *db,
                 const char *cypher,
                 uintptr_t cypher_len,
                 const char *params_json,
                 uintptr_t params_len,
                 struct HawdbBuffer *result_out,
                 struct HawdbBuffer *err_out);

/**
 * Run one SQL statement.
 *
 * `params_json` may be NULL or a JSON array of positional `$1`
 * parameters with the same value encoding as [`hawdb_query`]. Result
 * and error conventions match [`hawdb_query`].
 *
 * # Safety
 * Same contract as [`hawdb_query`].
 */
bool hawdb_query_sql(struct HawdbDatabase *db,
                     const char *sql,
                     uintptr_t sql_len,
                     const char *params_json,
                     uintptr_t params_len,
                     struct HawdbBuffer *result_out,
                     struct HawdbBuffer *err_out);

/**
 * Free a buffer returned by this library and zero the caller's
 * [`HawdbBuffer`] so a second call is a safe no-op. Passing NULL for
 * `buffer`, or a buffer whose `ptr` is NULL, is a no-op.
 *
 * # Safety
 * `buffer` must be NULL or point to a [`HawdbBuffer`] whose `ptr` was
 * allocated by this library and not already freed.
 */
void hawdb_buffer_free(struct HawdbBuffer *buffer);

/**
 * Copy the HawDB version string into `out`. The buffer is caller-owned
 * like every other [`HawdbBuffer`]: release it with
 * [`hawdb_buffer_free`].
 *
 * # Safety
 * `out` must be NULL or point to writable [`HawdbBuffer`] storage.
 */
void hawdb_version(struct HawdbBuffer *out);
