[package]
name = "hawdb-artifact"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
hawdb-core = { path = "../core", version = "0.3.0" }
hawdb-executor = { path = "../executor", version = "0.3.0" }
hawdb-qos = { path = "../qos", version = "0.3.0" }
