pub(super) const CORE_SEMANTIC_ALIAS_RULES: &[(&[&str], &[&str])] = &[
    (&["ahead_log", "write_ahead", "write_ahead_log"], &["wal"]),
    (&["ann"], &["approximate_nearest_neighbor"]),
    (
        &[
            "approximate_nearest",
            "nearest_neighbor",
            "approximate_nearest_neighbor",
        ],
        &["ann"],
    ),
    (&["compressed_sparse_column", "sparse_column"], &["csc"]),
    (&["compressed_sparse_row", "sparse_row"], &["csr"]),
    (
        &[
            "concurrency_control",
            "multi_version",
            "multi_version_concurrency_control",
        ],
        &["mvcc"],
    ),
    (&["csc"], &["compressed_sparse_column"]),
    (&["csr"], &["compressed_sparse_row"]),
    (&["full_text", "full_text_search", "text_search"], &["fts"]),
    (&["fts"], &["full_text_search", "text_search"]),
    (
        &["bulk_import", "database_import", "skein_import"],
        &["skein_lightning"],
    ),
    (
        &["checkpoint", "checkpointed"],
        &["snapshot", "storage_snapshot"],
    ),
    (&["content_stream", "contentstream"], &["value_stream"]),
    (
        &["relational_stream", "relationalstream", "sql_stream"],
        &["value_stream"],
    ),
    (
        &["graph_export", "graph_stream", "graphstream"],
        &["graphstream"],
    ),
    (
        &["skein_lightning", "lightning_import"],
        &["bulk_import", "database_import"],
    ),
    (&["graphstream"], &["graph_stream", "graph_export"]),
    (&["hybrid_retrieval"], &["hybrid_retrieve", "hybrid_search"]),
    (&["hybrid_retrieve", "hybrid_search"], &["hybrid_retrieval"]),
    (&["kg"], &["knowledge_graph"]),
    (&["knowledge_graph"], &["kg"]),
    (&["kuzu"], &["ladybug"]),
    (&["ladybug"], &["kuzu"]),
    (&["lance"], &["lancedb"]),
    (&["lancedb"], &["lance"]),
    (
        &[
            "log_structured",
            "log_structured_merge_tree",
            "merge_tree",
            "structured_merge",
        ],
        &["lsm"],
    ),
    (&["lsm"], &["log_structured_merge_tree"]),
    (&["mvcc"], &["multi_version_concurrency_control"]),
    (&["open_cypher"], &["cypher"]),
    (&["opencypher"], &["cypher", "open_cypher"]),
    (&["pg", "postgres"], &["postgresql"]),
    (&["postgresql"], &["postgres", "pg"]),
    (&["pg_vector", "pgvector"], &["vector_search"]),
    (
        &["projection_freshness", "projection_staleness"],
        &["freshness"],
    ),
    (
        &["rag"],
        &[
            "retrieval_augmented_generation",
            "graph_rag",
            "graph_retrieval",
        ],
    ),
    (&["wal"], &["write_ahead_log"]),
    (
        &["graph_rag"],
        &["rag", "retrieval_augmented_generation", "graph_retrieval"],
    ),
    (&["graphrag"], &["graph_rag", "rag", "graph_retrieval"]),
    (&["graph_retrieval"], &["graph_rag", "rag"]),
    (
        &[
            "retrieval_augmented",
            "augmented_generation",
            "retrieval_augmented_generation",
        ],
        &["rag", "graph_rag"],
    ),
    (
        &["reciprocal_rank", "rank_fusion", "reciprocal_rank_fusion"],
        &["rrf"],
    ),
    (&["rrf"], &["reciprocal_rank_fusion"]),
    (&["semantic_search", "vector_search"], &["pgvector"]),
    (
        &["snapshot", "storage_snapshot"],
        &["checkpoint", "checkpointed"],
    ),
    (&["value_stream", "valuestream"], &["content_stream"]),
];

pub(super) const NOWLEDGE_MEMORY_SEMANTIC_ALIAS_RULES: &[(&[&str], &[&str])] = &[
    (&["crystal"], &["crystallized memory", "synthesized memory"]),
    (&["crystallization", "crystallized"], &["crystal"]),
    (&["synthesized", "synthesis"], &["crystal"]),
    (&["synthesized from"], &["crystal", "sourced from"]),
    (&["episodic", "episodic provenance"], &["raw evidence"]),
    (&["raw evidence"], &["episodic provenance"]),
    (&["source provenance"], &["sourced from"]),
    (&["sourced from"], &["source provenance"]),
    (&["entity mention", "memory mention"], &["mentions"]),
    (&["mentions"], &["entity mention", "memory mention"]),
    (&["evolves"], &["memory evolution"]),
    (&["memory evolution", "evolution edge"], &["evolves"]),
    (&["ai summary"], &["community summary"]),
    (
        &["community summary", "summarized community"],
        &["ai summary"],
    ),
    (
        &[
            "memory-to-memory",
            "memory to memory",
            "memory_to_memory",
            "memory link",
            "memory links",
            "memorylink",
            "memorylinks",
            "linked memories",
            "memory relation",
            "memory relationship",
            "memory edge",
        ],
        &[
            "memory_relates_to",
            "relation_type",
            "semantic relation",
            "same_topic",
        ],
    ),
    (
        &["memory_relates_to", "relation_type", "same_topic"],
        &["memory link", "semantic relation"],
    ),
];
