[package]
name = "hawdb-telemetry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
opentelemetry = { version = "0.31", default-features = false, features = ["metrics"], optional = true }
hawdb-qos = { path = "../qos" }

[features]
default = []
opentelemetry = ["dep:opentelemetry"]
