[package]
name = "hawdb-nowledge-contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde = "1"
serde_json = "1"
hawdb-core = { path = "../core", version = "0.2.0" }
hawdb-qos = { path = "../qos", version = "0.2.0" }
hawdb-search = { path = "../search", version = "0.2.0", default-features = false }
hawdb-storage = { path = "../storage", version = "0.2.0" }
