[package]
name = "hawdb-nowledge-contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = "1"
serde_json = "1"
hawdb-core = { path = "../core" }
hawdb-qos = { path = "../qos" }
hawdb-search = { path = "../search", default-features = false }
hawdb-storage = { path = "../storage" }
