[package]
name = "hawdb-plan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hawdb-core = { path = "../core" }
hawdb-cypher = { path = "../cypher" }
hawdb-ddl = { path = "../ddl" }
hawdb-expression = { path = "../expression" }

[dev-dependencies]
serde_json = "1"
