[package]
name = "skein-plan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
skein-core = { path = "../core" }
skein-cypher = { path = "../cypher" }
skein-ddl = { path = "../ddl" }
skein-expression = { path = "../expression" }

[dev-dependencies]
serde_json = "1"
